package com.retrofrost.lattice.model

data class LatticeSettings(
    val sendOptionalDataToTelegram: Boolean = false,
    val hideIp: Boolean = true,
    val useTor: Boolean = true,
    val blockDirectFallback: Boolean = true,
    val disableP2PCalls: Boolean = true,
    val contactSync: Boolean = false,
    val linkPreviews: Boolean = false,
    val screenshotProtection: Boolean = true,
    val notificationContent: Boolean = false,
    val notificationsEnabled: Boolean = true,
    val notificationSound: Boolean = false,
    val notificationVibration: Boolean = false,
    val quietUi: Boolean = true,

    val autoDownloadPhotos: Boolean = false,
    val autoDownloadVideos: Boolean = false,
    val autoDownloadFiles: Boolean = false,
    val autoDownloadVoice: Boolean = false,
    val autoDownloadVideoMessages: Boolean = false,
    val autoplayVideo: Boolean = false,
    val autoplayGifs: Boolean = false,
    val animateStickers: Boolean = false,
    val loadProfilePictures: Boolean = true,
    val saveToGallery: Boolean = false,
    val stripLocationMetadata: Boolean = true,
    val preserveManualDownloads: Boolean = true,
    val hidePaidMedia: Boolean = true,
    val hidePaidReactions: Boolean = true,
    val hideStarUpsells: Boolean = true,

    val showSexualMaterial: Boolean = false,
    val blurSuspectedSexualMedia: Boolean = true,
    val hideSexualStickersGifs: Boolean = true,
    val hideSuggestiveEmojis: Boolean = true,
    val hideSuggestiveBotMessages: Boolean = true,
    val blockAdultSitePreviews: Boolean = true,
    val hideExplicitChatPreviews: Boolean = true,

    val goreFilter: Boolean = true,
    val blurSuspectedGore: Boolean = true,
    val hideGoreStickersGifs: Boolean = true,
    val hideGraphicBotMessages: Boolean = true,
    val blockShockSites: Boolean = true,

    val spamFilter: Boolean = true,
    val collapseRepeatedMessages: Boolean = true,
    val hideSuspiciousBotDms: Boolean = true,
    val scamLinkWarnings: Boolean = true,
    val autoReportSpam: Boolean = false,

    val swearingFilter: Boolean = false,
    val censorSwearingInsteadOfHide: Boolean = true,

    val dndEnabled: Boolean = false,
    val dndHideUnreadBadges: Boolean = true,
    val dndHideNotificationContent: Boolean = true,
    val dndDisableVibration: Boolean = true,
    val dndDisableSounds: Boolean = true,
    val dndAllowPinnedChats: Boolean = true
)
